### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by cometta** [amitsinha559/cordova-plugin-back-as-home#1]
Have you tested this in cordova 5.3.1 ? Below is my test results
1. tested on real android device, back button not working
2. test on emulator, debug with chrome, unable to find object 'backAsHome' in js console

**Comment by amitsinha559** [comment]
@cometta 

Yes, I have tested. I am using it in my app. Try this code. Add this in `$ionicPlatform.ready`

$ionicPlatform.registerBackButtonAction(function(e){
    backAsHome.trigger(function(){
        console.log("Success");
    }, function(){
        console.log("Error");
    });
    e.preventDefault();
},101);

**Comment by roblav96** [comment]
This plugin works flawless! Such an incredibly useful plugin. Thanks mate!!!
