### ISSUE TITLE
Audio not run on background

### ISSUE THREAD

**Issue by Neotrixsx** [amitsinha559/cordova-plugin-back-as-home#2]
I use NativeAudio plugin for my audio application and I use your plugin for background run. But when i click back button application goes minimize but audio pause. I need to know that, are you using Cordova media plugin or NativeAudio plugin. Please help

**Comment by amitsinha559** [comment]
I have used Cordova Media Plugin

**Comment by Neotrixsx** [comment]
if you have any sample code please provide me.

**Comment by amitsinha559** [comment]
I have used the same code.. which is available here https://github.com/amitsinha559/cordova-plugin-back-as-home
